#ifdef __cplusplus
#if __has_include(<bits/stdc++.h>)
#include <bits/stdc++.h>
#endif
#endif
#define 整型 int
#define 字符 char
#define 短的 short
#define 长的 long
#define 无符号 unsigned
#define 有符号 signed
#define 布尔 bool
#define 浮点 float
#define 双精度浮点 double
#define 空指针 nullptr
#define 空指针类型 nullptr_t
#define 主函数 main
#define 标准库 std
#define 矢量 vector
#define 数组 array
#define 堆栈 stack
#define 队列 queue
#define 一对 pair
#define 制作一对 make_pair
#define 元组 tuple
#define 制作元组 make_tuple
#define 多选组 variant
#define 可选项 optional
#define 制作可选项 make_optional
#define 可选项为空 nullopt
#define 任意 any
#define 集合 set
#define 字典 map
#define 无序集合 unordered_set
#define 无序字典 unordered_map
#define 函数 function
#define 排序 sort
#define 开始 begin
#define 结束 end
#define 大小 size
#define 调整大小 resize
#define 数据 data
#define 定义 define
#define 包含 include
#define 定义了 defined
#define 找得到头文件 __has_include
#define 位于 at
#define 寻找 find
#define 变换 transform
#define 含有 contains
#define 插入 insert
#define 构造 emplace
#define 推入 push
#define 推入至末尾 push_back
#define 构造至末尾 emplace_back
#define 移动 move
#define 转发 forward
#define 子字符串 substr
#define 以之开始 starts_with
#define 以之结束 ends_with
#define 独占指针 unique_ptr
#define 创建独占指针 make_unique
#define 共享指针 shared_ptr
#define 创建共享指针 make_shared
#define 弱指针 weak_ptr
#define 创建弱指针 make_weak
#define 运算符 operator
#define 结构体 struct
#define 定义类 class
#define 类型名 typename
#define 模板 template
#define 输入文件流 ifstream
#define 输出文件流 ofstream
#define 字符串流 stringstream
#define 输入字符串流 istringstream
#define 输出字符串流 ostringstream
#define 文件之流 fstream
#define 字符串之流 sstream
#define 输入输出之流 iostream
#define 标准输入输出库 cstdio
#define 标准函数库 cstdlib
#define 标准数学库 cmath
#define 通用算法库 algorithm
#define 最大 max
#define 最小 min
#define 字符串转整数 stoi
#define 转为字符串 to_string
#define 字符串 string
#define 字符串区间 string_view
#define 内联 inline
#define 静态 static
#define 编译期常值 constexpr
#define 公开 public
#define 保护 protected
#define 私有 private
#define 本对象 this
#define 如果 if
#define 否则 else
#define 打断 break
#define 执行 do
#define 当满足 while
#define 循环 for
#define 使用 using
#define 名字空间 namespace
#define 获取类型 decltype
#define 自动 auto
#define 常值 const
#define 标准输入流 cin
#define 标准输出流 cout
#define 错误输出流 cerr
#define 行结束符 endl
#define 返回 return
